package org.evochora.datapipeline.api.analytics;

import com.typesafe.config.Config;
import org.evochora.datapipeline.api.contracts.SimulationMetadata;
import org.evochora.datapipeline.api.contracts.TickData;

import java.util.List;

/**
 * Interface for Analytics Plugins.
 * Instances are created per-service, so they do NOT need to be thread-safe.
 */
public interface IAnalyticsPlugin {
    /**
     * Configure the plugin from HOCON.
     * Must read: samplingInterval, lodFactor, lodLevels.
     *
     * @param config The plugin-specific configuration object
     */
    void configure(Config config);

    /**
     * Initialize plugin for a specific run.
     * Called once per run (or per service start).
     *
     * @param context Provides access to writers and metadata.
     */
    void initialize(IAnalyticsContext context);

    /**
     * Process a batch of tick data.
     * Implementation should aggregate data and write to storage via the context/writer.
     * Must handle LOD generation and file rotation (large batches).
     * <p>
     * Error Handling: Throw RuntimeException to fail the batch (trigger redelivery).
     *
     * @param batch List of ticks to process
     */
    void processBatch(List<TickData> batch);

    /**
     * Called when indexer shuts down or finishes a run.
     * Useful for flushing buffers or closing open files.
     */
    void onFinish();

    /**
     * Returns the manifest entry describing the metric generated by this plugin.
     * The Indexer writes this to `{metric_id}/metadata.json` (idempotently).
     *
     * @return The manifest entry or null if plugin produces no visible metric
     */
    ManifestEntry getManifestEntry();
}

